### ISSUE TITLE
hi 兄弟，我也正想收集基金数据

### ISSUE THREAD

**Issue by jun-lu** [mindcont/Fund-DB#1]
hi 兄弟，我也正想收集基金数据。一起合作吧

**Comment by mindcont** [comment]
@jun-lu 
哈哈，可以，不过最近我正在实习，得国庆后把，设置自动爬虫脚本每天定时提交。
本来想打算搜集公募基金 每日净值数据，看看能不能从中发现些规律。后来发现，我天真了，大A股完全不按套路，加上中美贸易战的关系，和之前完全不一样了。现在就是看基本面，比如医药啊，白酒啊，大盘指数类的基金可以定投布局，会涨起来的😜

**Comment by mindcont** [comment]
干的漂亮！👍
